#Logistic_Regression:
  #class_weight: "balanced"
  #max_iter: 1000
  #penalty: l2
  #C: 1.0
  #solver: "lbfgs"
  #random_state: 42


random_forest:
  n_estimators: 300
  max_depth: 5
  random_state: 42
  class_weight: "balanced"

#XGBClassifier:
  #n_estimators: 100
  #learning_rate: 0.1
  #max_depth: 4
  #random_state: 42
